        # self.verticalLayout_17 = QtWidgets.QVBoxLayout(self.frame_13)
        # self.verticalLayout_17.setObjectName("verticalLayout_17")
        # self.frame_23 = QtWidgets.QFrame(self.frame_13)
        # self.frame_23.setMaximumSize(QtCore.QSize(16777215, 40))
        # self.frame_23.setFrameShape(QtWidgets.QFrame.StyledPanel)
        # self.frame_23.setFrameShadow(QtWidgets.QFrame.Raised)
        # self.frame_23.setObjectName("frame_23")
        # self.verticalLayout_18 = QtWidgets.QVBoxLayout(self.frame_23)
        # self.verticalLayout_18.setContentsMargins(0, 0, 0, 0)
        # self.verticalLayout_18.setSpacing(0)
        # self.verticalLayout_18.setObjectName("verticalLayout_18")
        # self.label_8 = QtWidgets.QLabel(self.frame_23)
        # self.label_8.setObjectName("label_8")
        # self.verticalLayout_18.addWidget(self.label_8)
        # self.verticalLayout_17.addWidget(self.frame_23)
        # self.frame_24 = QtWidgets.QFrame(self.frame_13)
        # self.frame_24.setFrameShape(QtWidgets.QFrame.StyledPanel)
        # self.frame_24.setFrameShadow(QtWidgets.QFrame.Raised)
        # self.frame_24.setObjectName("frame_24")
        # self.horizontalLayout_8 = QtWidgets.QHBoxLayout(self.frame_24)
        # self.horizontalLayout_8.setContentsMargins(0, 0, 0, 0)
        # self.horizontalLayout_8.setSpacing(3)
        # self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        # self.label_9 = QtWidgets.QLabel(self.frame_24)
        # self.label_9.setMaximumSize(QtCore.QSize(200, 16777215))
        # self.label_9.setText("")
        # self.label_9.setPixmap(QtGui.QPixmap(":/newPrefix/safe.png"))
        # self.label_9.setScaledContents(True)
        # self.label_9.setObjectName("label_9")
        # self.horizontalLayout_8.addWidget(self.label_9)
        # self.label_10 = QtWidgets.QLabel(self.frame_24)
        # self.label_10.setObjectName("label_10")
        # self.horizontalLayout_8.addWidget(self.label_10)
        # self.verticalLayout_17.addWidget(self.frame_24)